### ISSUE TITLE
error in your give command 

### ISSUE THREAD

**Issue by r0x5r** [tarunKoyalwar/nestle#3]
'(query|mutation)\s+[a-zA-Z]+[0-9]*[a-zA-Z]+(\([^(\(|\))]+\))*\s*[{:nested:}]'

A Wrapper around regexp.Regexp that supports Nested Symbols/brackets
Use syntax `[(:nested:)]` for nested groups

**Comment by tarunKoyalwar** [comment]
Hii @rohit0x5 , It looks like you missed some chars while copying the regex. The correct regex is 
~~~
'(query|mutation)\s+[a-zA-Z]+[0-9]*[a-zA-Z]+(\([^(\(|\))]+\))*\s*[{:nested:}]' | sed 's/\\n/\n/g'
~~~
As you can see you are missing some literals. This regex is also available on README.md page of repository .
